CREATE TABLE `orders` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`order_id` varchar(255) NOT NULL,
	`order_status` varchar(64),
	`order_time` timestamp,
	`complete_time` timestamp,
	`click_time` timestamp,
	`shop_name` varchar(255),
	`product_id` varchar(255),
	`product_name` text,
	`quantity` int DEFAULT 0,
	`currency` varchar(16) DEFAULT 'VND',
	`purchase_value` bigint,
	`actual_commission` bigint,
	`sub_id` varchar(255),
	`sub1` varchar(255),
	`sub2` varchar(255),
	`sub3` varchar(255),
	`sub4` varchar(255),
	`sub5` varchar(255),
	`user_id` varchar(64),
	`commission_rate` int DEFAULT 0,
	`user_commission` bigint DEFAULT 0,
	`is_paid` int DEFAULT 0,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `orders_id` PRIMARY KEY(`id`)
);
