<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { message } from 'ant-design-vue'
import { ReloadOutlined, WalletOutlined } from '@ant-design/icons-vue'
import { api, type ApiResponse } from '../services/api'
type User = { id:string; name:string|null; tracking_code:string }
type Tx = { id:number; amount:number; type:string; status:string; reference_id:string|null; description:string|null; created_at:string; user:User|null }
const users=ref<User[]>([]), userId=ref(''), rows=ref<Tx[]>([]), loading=ref(false), page=ref(1), limit=ref(20), total=ref(0)
const type=ref(''), status=ref(''), startDate=ref(''), endDate=ref('')
const overview=ref<{available_balance:number;pending_balance:number;total_paid:number;completed_orders:number}|null>(null)
const money=(v:number)=>new Intl.NumberFormat('vi-VN').format(Math.abs(v||0))+'đ'
const statusMap:Record<string,string>={pending:'Chờ xử lý',success:'Thành công',rejected:'Từ chối'}
const fetchUsers=async()=>{ const r=await api.get<ApiResponse<User[]>>('/api/admin/users'); users.value=r.data.data||[]; if(!userId.value&&users.value.length) userId.value=users.value[0].id }
const fetchData=async()=>{loading.value=true;try{const params:Record<string,string|number>={page:page.value,limit:limit.value};if(userId.value)params.userId=userId.value;if(type.value)params.type=type.value;if(status.value)params.status=status.value;if(startDate.value)params.startDate=startDate.value;if(endDate.value)params.endDate=endDate.value;const [list,info]=await Promise.all([api.get<ApiResponse<{transactions:Tx[];total:number}>>('/api/admin/transactions',{params}),userId.value?api.get<ApiResponse<typeof overview.value>>(`/api/admin/transactions/overview/${userId.value}`):Promise.resolve(null)]);rows.value=list.data.data?.transactions||[];total.value=list.data.data?.total||0;overview.value=info?.data.data||null}catch{message.error('Không thể tải lịch sử giao dịch.')}finally{loading.value=false}}
onMounted(async()=>{await fetchUsers();await fetchData()});watch([userId,type,status,limit],()=>{page.value=1;fetchData()})
const columns=[{title:'Thời gian',key:'time',width:155},{title:'Mã / Nội dung',key:'content',width:300},{title:'Loại giao dịch',key:'type',width:150},{title:'Số tiền',key:'amount',width:150},{title:'Trạng thái',key:'status',width:130}]
const selectedUser=computed(()=>users.value.find(x=>x.id===userId.value))
</script>
<template><div class="flex flex-col gap-6 pb-12">
  <div><h2 class="text-lg font-bold text-slate-800">Lịch sử giao dịch</h2><p class="mt-1 text-[13px] text-slate-500">Theo dõi giao dịch hoa hồng và rút tiền của người dùng.</p></div>
  <a-card :bordered="false" class="!rounded-2xl"><div class="grid gap-4 lg:grid-cols-[300px_1fr] lg:items-end"><div><label class="mb-2 block text-[11px] font-bold uppercase text-slate-500">Người dùng</label><a-select v-model:value="userId" show-search option-filter-prop="label" class="w-full" :options="users.map(u=>({value:u.id,label:`${u.name||'Người dùng'} · ${u.tracking_code}`}))" /></div><div class="text-xs text-slate-500">Đang xem: <b class="text-slate-800">{{selectedUser?.name||'Chưa chọn người dùng'}}</b></div></div></a-card>
  <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div v-for="card in [{l:'Số dư khả dụng',v:money(overview?.available_balance||0)},{l:'Đang chờ rút',v:money(overview?.pending_balance||0)},{l:'Đã rút',v:money(overview?.total_paid||0)},{l:'Đơn hoàn thành',v:String(overview?.completed_orders||0)}]" :key="card.l" class="rounded-2xl bg-white p-5 shadow-sm"><WalletOutlined class="mb-3 text-xl !text-[#ee4d2d]"/><div class="text-xs font-semibold text-slate-500">{{card.l}}</div><div class="mt-1 text-xl font-black text-slate-800">{{card.v}}</div></div></div>
  <a-card :bordered="false" :body-style="{padding:0}" class="overflow-hidden !rounded-2xl"><div class="flex flex-wrap items-end gap-3 border-b border-slate-100 p-4"><a-select v-model:value="type" class="w-40" :options="[{label:'Tất cả loại',value:''},{label:'Hoa hồng',value:'commission'},{label:'Rút tiền',value:'withdrawal'}]"/><a-select v-model:value="status" class="w-40" :options="[{label:'Tất cả trạng thái',value:''},{label:'Chờ xử lý',value:'pending'},{label:'Thành công',value:'success'},{label:'Từ chối',value:'rejected'}]"/><input v-model="startDate" type="date" class="h-8 rounded-md border border-slate-300 px-3 text-xs"/><input v-model="endDate" type="date" class="h-8 rounded-md border border-slate-300 px-3 text-xs"/><a-button type="primary" class="!inline-flex !h-8 !items-center !justify-center !gap-1.5 !border-none !bg-[#ee4d2d] hover:!bg-[#d63d1e]" @click="page=1;fetchData()"><ReloadOutlined/><span class="!text-white">Áp dụng</span></a-button></div>
  <a-table :columns="columns" :data-source="rows" :loading="loading" :pagination="false" row-key="id" :scroll="{x:900}"><template #bodyCell="{column,record}"><template v-if="column.key==='time'"><b class="text-xs">{{new Date(record.created_at).toLocaleDateString('vi-VN')}}</b><div class="text-[10px] text-slate-400">{{new Date(record.created_at).toLocaleTimeString('vi-VN')}}</div></template><template v-else-if="column.key==='content'"><div class="text-xs font-bold">{{record.reference_id||'#'+record.id}}</div><div class="mt-1 text-[11px] text-slate-500">{{record.description||'Không có mô tả'}}</div></template><template v-else-if="column.key==='type'"><span class="rounded-full px-2.5 py-1 text-xs font-bold" :class="record.type==='commission'?'bg-orange-50 text-[#ee4d2d]':'bg-blue-50 text-blue-600'">{{record.type==='commission'?'Hoa hồng':'Rút tiền'}}</span></template><template v-else-if="column.key==='amount'"><b :class="record.amount>=0?'text-emerald-600':'text-rose-600'">{{record.amount>=0?'+':'-'}}{{money(record.amount)}}</b></template><template v-else-if="column.key==='status'"><span class="text-xs font-bold">{{statusMap[record.status]||record.status}}</span></template></template></a-table>
  <div class="flex justify-end border-t border-slate-100 p-4"><a-pagination :current="page" :total="total" :page-size="limit" @change="(p:number)=>{page=p;fetchData()}"/></div></a-card>
</div></template>
